### ISSUE TITLE
BubbleWrap Update

### ISSUE THREAD

**Issue by cspeer** [holgersindbaek/status_bar#3]
Hey,

do you mind updating the Gemspec to use the newest version of BW? :)

Cheers,
Chris

**Comment by holgersindbaek** [comment]
Hi Chris  

I'm pressed for time at the moment, but your welcome to send a PR.   

## 

All the best

Holger Sindbaek
Holgersindbaek.com

**Comment by cspeer** [comment]
Done :) #4
